# Generated by Django 4.2.7 on 2024-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories_images",
                verbose_name="Изображение",
            ),
        ),
    ]
